import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Workspace } from '../src/index.ts';
import { TELEMETRY_FIELDS } from '../src/execution/telemetry.ts';
import { cleanup, project, FEATURE, REQUIREMENT, TASK } from './helpers.ts';

const FILES = ['CLAUDE.md', 'AGENTS.md', 'CODEX.md', 'GEMINI.md'];
const files = {
  'f.yaml': FEATURE, 'r.yaml': REQUIREMENT, 't.yaml': TASK,
  'rule.yaml': 'id: RULE-0001\nkind: rule\ntitle: Money is integer minor units\nstatus: active\napplies_to: [FEAT-0001]\nsummary: No floating point.\n',
};

test('compile generates every agent instruction file', () => {
  const root = project(files);
  const ws = Workspace.load(root);
  assert.ok(ws.ok);
  ws.value.compile();
  for (const f of FILES) assert.ok(existsSync(join(root, f)), `${f} missing`);
  ws.value.close(); cleanup(root);
});

test('instruction files regenerate identically', () => {
  const root = project(files);
  const ws = Workspace.load(root);
  assert.ok(ws.ok);
  ws.value.compile();
  const first = FILES.map((f) => readFileSync(join(root, f), 'utf8'));
  ws.value.compile(true);
  const second = FILES.map((f) => readFileSync(join(root, f), 'utf8'));
  assert.deepEqual(second, first);
  ws.value.close(); cleanup(root);
});

test('one template serves every agent: files differ only in the preamble', () => {
  const root = project(files);
  const ws = Workspace.load(root);
  assert.ok(ws.ok);
  ws.value.compile();
  const bodies = FILES.map((f) => readFileSync(join(root, f), 'utf8').split('\n').filter((l) => !l.startsWith('Instructions for')).join('\n'));
  for (const b of bodies) assert.equal(b, bodies[0]);
  ws.value.close(); cleanup(root);
});

test('generated files carry a do-not-edit banner and the project rules', () => {
  const root = project(files);
  const ws = Workspace.load(root);
  assert.ok(ws.ok);
  ws.value.compile();
  const text = readFileSync(join(root, 'CLAUDE.md'), 'utf8');
  assert.match(text, /GENERATED BY annona compile/);
  assert.match(text, /RULE-0001/);
  assert.match(text, /annona context/);
  assert.match(text, /engineering memory/);
  assert.match(text, /deterministic context compiler/);
  assert.match(text, /If the project uses Spec Kit/);
  assert.match(text, /Use Spec Kit for `specify`, `plan`, and `tasks`/);
  ws.value.close(); cleanup(root);
});

test('telemetry stays inside the disposable runtime', () => {
  const root = project(files);
  const ws = Workspace.load(root);
  assert.ok(ws.ok);
  ws.value.compile();
  ws.value.context('TASK-0001');
  const log = join(root, '.annona', 'telemetry.jsonl');
  assert.ok(existsSync(log));
  const events = readFileSync(log, 'utf8').trim().split('\n').map((l) => JSON.parse(l) as Record<string, unknown>);
  assert.ok(events.some((e) => e['command'] === 'compile'));
  assert.ok(events.some((e) => e['command'] === 'context' && e['verdict'] !== undefined));
  // engineering metrics only: no paths, no identifiers, no free text
  for (const e of events)
    for (const [k, v] of Object.entries(e))
      assert.ok((TELEMETRY_FIELDS as readonly string[]).includes(k), `unexpected telemetry field ${k}=${String(v)}`);
  ws.value.close(); cleanup(root);
});
